import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { createCashTransactionSchema } from "@/lib/validators";

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const body = await request.json();
  const parsed = createCashTransactionSchema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });
  }

  const { type, amount, note } = parsed.data;

  // Verify account exists
  const account = await prisma.account.findUnique({
    where: { id },
  });

  if (!account) {
    return NextResponse.json({ error: "Account not found" }, { status: 404 });
  }

  // Create the transaction
  const transaction = await prisma.cashTransaction.create({
    data: {
      accountId: id,
      type,
      amount,
      note,
    },
  });

  // Calculate actual amount diff based on type
  let amountDiff = 0;
  if (type === "DEPOSIT") {
    amountDiff = amount;
  } else if (type === "WITHDRAWAL") {
    amountDiff = -amount;
  } else if (type === "EDIT") {
    amountDiff = amount; // Edit assumes amount already represents the explicit difference from old value if created manually, wait.
    // Actually, in the UI for cash-transactions POST, we shouldn't really send EDIT unless we want to apply a raw diff. Let's assume amount is a raw diff.
    // If it's an explicit EDIT generated by the UI with a specific + or - diff.
  }

  // Update account balance
  await prisma.account.update({
    where: { id },
    data: {
      cashBalance: {
        increment: amountDiff,
      },
    },
  });

  return NextResponse.json(transaction, { status: 201 });
}
